# Generated by Django 2.1.4 on 2018-12-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1)),
                ('habit1', models.CharField(max_length=25)),
                ('habit2', models.CharField(max_length=25)),
                ('habit3', models.CharField(max_length=25)),
                ('habit4', models.CharField(max_length=25)),
                ('habit5', models.CharField(max_length=25)),
                ('habit6', models.CharField(max_length=25)),
                ('habit7', models.CharField(max_length=25)),
                ('habit8', models.CharField(max_length=25)),
            ],
        ),
    ]
